# Kubernetes ConfigMap for Customer Success AI Platform Web Frontend - Staging Environment
# Version: v1
# Dependencies: k8s-core v1

apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: customer-success-ai-staging
  labels:
    app: customer-success-ai
    component: web
    environment: staging
data:
  # Node environment configuration
  NODE_ENV: "staging"

  # API and Service URLs
  VITE_API_URL: "https://api-staging.customer-success-ai.com"
  
  # Blitzy Integration Configuration
  VITE_BLITZY_API_KEY: "${BLITZY_API_KEY}"
  VITE_BLITZY_PROJECT_ID: "${BLITZY_PROJECT_ID}"
  VITE_BLITZY_ENV: "staging"
  
  # Authentication Configuration
  VITE_AUTH0_DOMAIN: "${AUTH0_DOMAIN}"
  VITE_AUTH0_CLIENT_ID: "${AUTH0_CLIENT_ID}"
  VITE_AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
  
  # Monitoring and Error Tracking
  VITE_SENTRY_DSN: "${SENTRY_DSN}"
  VITE_DATADOG_APP_ID: "${DATADOG_APP_ID}"
  VITE_DATADOG_CLIENT_TOKEN: "${DATADOG_CLIENT_TOKEN}"
  
  # Feature Flags
  VITE_FEATURE_ML_PREDICTIONS: "true"
  VITE_FEATURE_PLAYBOOK_AUTOMATION: "true"
  VITE_FEATURE_CUSTOM_REPORTS: "true"
  
  # Logging and Monitoring
  VITE_LOG_LEVEL: "debug"
  VITE_PERFORMANCE_MONITORING: "true"
  VITE_ERROR_REPORTING: "true"
  
  # Security and Session Management
  VITE_SESSION_TIMEOUT: "3600"  # 1 hour in seconds
  
  # Performance and Resource Limits
  VITE_MAX_UPLOAD_SIZE: "10485760"  # 10MB in bytes
  VITE_CACHE_TTL: "300"  # 5 minutes in seconds