version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        - NODE_ENV=development
        - VITE_APP_NAME=customer-success-ai
        - VITE_API_VERSION=v1
        - VITE_BLITZY_ENVIRONMENT=development
    ports:
      - "3000:3000"  # Main application port
      - "24678:24678"  # Vite HMR port
    volumes:
      - .:/app:cached  # Source code mounting
      - /app/node_modules  # Node modules volume
      - ./logs:/app/logs:delegated  # Logs directory
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - VITE_BLITZY_CLIENT_ID=${VITE_BLITZY_CLIENT_ID}
      - VITE_BLITZY_SSO_PROVIDER=blitzy-enterprise
      - VITE_ENABLE_MFA=true
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=24678
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - customer-success-network

networks:
  customer-success-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    driver_opts:
      com.docker.network.bridge.name: cs-network
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind