# Prometheus configuration file for Customer Success AI Platform
# Version: v2.45.0
# Purpose: Enterprise monitoring and metrics collection

global:
  # Global settings for all scrape configurations
  scrape_interval: 15s     # Default interval between scrapes
  evaluation_interval: 15s  # Default interval for rule evaluation
  scrape_timeout: 10s      # Timeout for individual scrapes

# Load rules from files matching the pattern
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configuration for monitoring targets
scrape_configs:
  # Self-monitoring of Prometheus server
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for infrastructure metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Backend services monitoring
  - job_name: 'backend-services'
    metrics_path: '/metrics'
    scrape_interval: 10s  # More frequent scraping for critical services
    static_configs:
      - targets: ['backend:8000']
        labels:
          service: 'customer-success-ai'

  # ML services monitoring
  - job_name: 'ml-services'
    metrics_path: '/metrics'
    scrape_interval: 30s  # Less frequent scraping for ML services
    static_configs:
      - targets: ['ml-service:8001']
        labels:
          service: 'prediction-engine'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']